=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class AssistantMessage < ApiModelBase
    attr_accessor :id

    attr_accessor :session_id

    attr_accessor :role

    attr_accessor :time

    attr_accessor :error

    attr_accessor :parent_id

    attr_accessor :model_id

    attr_accessor :provider_id

    attr_accessor :mode

    attr_accessor :agent

    attr_accessor :path

    attr_accessor :summary

    attr_accessor :cost

    attr_accessor :tokens

    attr_accessor :finish

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'session_id' => :'sessionID',
        :'role' => :'role',
        :'time' => :'time',
        :'error' => :'error',
        :'parent_id' => :'parentID',
        :'model_id' => :'modelID',
        :'provider_id' => :'providerID',
        :'mode' => :'mode',
        :'agent' => :'agent',
        :'path' => :'path',
        :'summary' => :'summary',
        :'cost' => :'cost',
        :'tokens' => :'tokens',
        :'finish' => :'finish'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'session_id' => :'String',
        :'role' => :'String',
        :'time' => :'AssistantMessageTime',
        :'error' => :'AssistantMessageError',
        :'parent_id' => :'String',
        :'model_id' => :'String',
        :'provider_id' => :'String',
        :'mode' => :'String',
        :'agent' => :'String',
        :'path' => :'AssistantMessagePath',
        :'summary' => :'Boolean',
        :'cost' => :'Float',
        :'tokens' => :'AssistantMessageTokens',
        :'finish' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::AssistantMessage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::AssistantMessage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'session_id')
        self.session_id = attributes[:'session_id']
      else
        self.session_id = nil
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      else
        self.role = nil
      end

      if attributes.key?(:'time')
        self.time = attributes[:'time']
      else
        self.time = nil
      end

      if attributes.key?(:'error')
        self.error = attributes[:'error']
      end

      if attributes.key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      else
        self.parent_id = nil
      end

      if attributes.key?(:'model_id')
        self.model_id = attributes[:'model_id']
      else
        self.model_id = nil
      end

      if attributes.key?(:'provider_id')
        self.provider_id = attributes[:'provider_id']
      else
        self.provider_id = nil
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      else
        self.mode = nil
      end

      if attributes.key?(:'agent')
        self.agent = attributes[:'agent']
      else
        self.agent = nil
      end

      if attributes.key?(:'path')
        self.path = attributes[:'path']
      else
        self.path = nil
      end

      if attributes.key?(:'summary')
        self.summary = attributes[:'summary']
      end

      if attributes.key?(:'cost')
        self.cost = attributes[:'cost']
      else
        self.cost = nil
      end

      if attributes.key?(:'tokens')
        self.tokens = attributes[:'tokens']
      else
        self.tokens = nil
      end

      if attributes.key?(:'finish')
        self.finish = attributes[:'finish']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @session_id.nil?
        invalid_properties.push('invalid value for "session_id", session_id cannot be nil.')
      end

      if @role.nil?
        invalid_properties.push('invalid value for "role", role cannot be nil.')
      end

      if @time.nil?
        invalid_properties.push('invalid value for "time", time cannot be nil.')
      end

      if @parent_id.nil?
        invalid_properties.push('invalid value for "parent_id", parent_id cannot be nil.')
      end

      if @model_id.nil?
        invalid_properties.push('invalid value for "model_id", model_id cannot be nil.')
      end

      if @provider_id.nil?
        invalid_properties.push('invalid value for "provider_id", provider_id cannot be nil.')
      end

      if @mode.nil?
        invalid_properties.push('invalid value for "mode", mode cannot be nil.')
      end

      if @agent.nil?
        invalid_properties.push('invalid value for "agent", agent cannot be nil.')
      end

      if @path.nil?
        invalid_properties.push('invalid value for "path", path cannot be nil.')
      end

      if @cost.nil?
        invalid_properties.push('invalid value for "cost", cost cannot be nil.')
      end

      if @tokens.nil?
        invalid_properties.push('invalid value for "tokens", tokens cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @session_id.nil?
      return false if @role.nil?
      role_validator = EnumAttributeValidator.new('String', ["assistant"])
      return false unless role_validator.valid?(@role)
      return false if @time.nil?
      return false if @parent_id.nil?
      return false if @model_id.nil?
      return false if @provider_id.nil?
      return false if @mode.nil?
      return false if @agent.nil?
      return false if @path.nil?
      return false if @cost.nil?
      return false if @tokens.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] session_id Value to be assigned
    def session_id=(session_id)
      if session_id.nil?
        fail ArgumentError, 'session_id cannot be nil'
      end

      @session_id = session_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] role Object to be assigned
    def role=(role)
      validator = EnumAttributeValidator.new('String', ["assistant"])
      unless validator.valid?(role)
        fail ArgumentError, "invalid value for \"role\", must be one of #{validator.allowable_values}."
      end
      @role = role
    end

    # Custom attribute writer method with validation
    # @param [Object] time Value to be assigned
    def time=(time)
      if time.nil?
        fail ArgumentError, 'time cannot be nil'
      end

      @time = time
    end

    # Custom attribute writer method with validation
    # @param [Object] parent_id Value to be assigned
    def parent_id=(parent_id)
      if parent_id.nil?
        fail ArgumentError, 'parent_id cannot be nil'
      end

      @parent_id = parent_id
    end

    # Custom attribute writer method with validation
    # @param [Object] model_id Value to be assigned
    def model_id=(model_id)
      if model_id.nil?
        fail ArgumentError, 'model_id cannot be nil'
      end

      @model_id = model_id
    end

    # Custom attribute writer method with validation
    # @param [Object] provider_id Value to be assigned
    def provider_id=(provider_id)
      if provider_id.nil?
        fail ArgumentError, 'provider_id cannot be nil'
      end

      @provider_id = provider_id
    end

    # Custom attribute writer method with validation
    # @param [Object] mode Value to be assigned
    def mode=(mode)
      if mode.nil?
        fail ArgumentError, 'mode cannot be nil'
      end

      @mode = mode
    end

    # Custom attribute writer method with validation
    # @param [Object] agent Value to be assigned
    def agent=(agent)
      if agent.nil?
        fail ArgumentError, 'agent cannot be nil'
      end

      @agent = agent
    end

    # Custom attribute writer method with validation
    # @param [Object] path Value to be assigned
    def path=(path)
      if path.nil?
        fail ArgumentError, 'path cannot be nil'
      end

      @path = path
    end

    # Custom attribute writer method with validation
    # @param [Object] cost Value to be assigned
    def cost=(cost)
      if cost.nil?
        fail ArgumentError, 'cost cannot be nil'
      end

      @cost = cost
    end

    # Custom attribute writer method with validation
    # @param [Object] tokens Value to be assigned
    def tokens=(tokens)
      if tokens.nil?
        fail ArgumentError, 'tokens cannot be nil'
      end

      @tokens = tokens
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          session_id == o.session_id &&
          role == o.role &&
          time == o.time &&
          error == o.error &&
          parent_id == o.parent_id &&
          model_id == o.model_id &&
          provider_id == o.provider_id &&
          mode == o.mode &&
          agent == o.agent &&
          path == o.path &&
          summary == o.summary &&
          cost == o.cost &&
          tokens == o.tokens &&
          finish == o.finish
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, session_id, role, time, error, parent_id, model_id, provider_id, mode, agent, path, summary, cost, tokens, finish].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
