=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  # TUI specific settings
  class ConfigTui < ApiModelBase
    # TUI scroll speed
    attr_accessor :scroll_speed

    attr_accessor :scroll_acceleration

    # Control diff rendering style: 'auto' adapts to terminal width, 'stacked' always shows single column
    attr_accessor :diff_style

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'scroll_speed' => :'scroll_speed',
        :'scroll_acceleration' => :'scroll_acceleration',
        :'diff_style' => :'diff_style'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'scroll_speed' => :'Float',
        :'scroll_acceleration' => :'ConfigTuiScrollAcceleration',
        :'diff_style' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::ConfigTui` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::ConfigTui`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'scroll_speed')
        self.scroll_speed = attributes[:'scroll_speed']
      end

      if attributes.key?(:'scroll_acceleration')
        self.scroll_acceleration = attributes[:'scroll_acceleration']
      end

      if attributes.key?(:'diff_style')
        self.diff_style = attributes[:'diff_style']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@scroll_speed.nil? && @scroll_speed < 0.001
        invalid_properties.push('invalid value for "scroll_speed", must be greater than or equal to 0.001.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@scroll_speed.nil? && @scroll_speed < 0.001
      diff_style_validator = EnumAttributeValidator.new('String', ["auto", "stacked"])
      return false unless diff_style_validator.valid?(@diff_style)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] scroll_speed Value to be assigned
    def scroll_speed=(scroll_speed)
      if scroll_speed.nil?
        fail ArgumentError, 'scroll_speed cannot be nil'
      end

      if scroll_speed < 0.001
        fail ArgumentError, 'invalid value for "scroll_speed", must be greater than or equal to 0.001.'
      end

      @scroll_speed = scroll_speed
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] diff_style Object to be assigned
    def diff_style=(diff_style)
      validator = EnumAttributeValidator.new('String', ["auto", "stacked"])
      unless validator.valid?(diff_style)
        fail ArgumentError, "invalid value for \"diff_style\", must be one of #{validator.allowable_values}."
      end
      @diff_style = diff_style
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          scroll_speed == o.scroll_speed &&
          scroll_acceleration == o.scroll_acceleration &&
          diff_style == o.diff_style
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [scroll_speed, scroll_acceleration, diff_style].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
