=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class FileContentPatch < ApiModelBase
    attr_accessor :old_file_name

    attr_accessor :new_file_name

    attr_accessor :old_header

    attr_accessor :new_header

    attr_accessor :hunks

    attr_accessor :index

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'old_file_name' => :'oldFileName',
        :'new_file_name' => :'newFileName',
        :'old_header' => :'oldHeader',
        :'new_header' => :'newHeader',
        :'hunks' => :'hunks',
        :'index' => :'index'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'old_file_name' => :'String',
        :'new_file_name' => :'String',
        :'old_header' => :'String',
        :'new_header' => :'String',
        :'hunks' => :'Array<FileContentPatchHunksInner>',
        :'index' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::FileContentPatch` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::FileContentPatch`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'old_file_name')
        self.old_file_name = attributes[:'old_file_name']
      else
        self.old_file_name = nil
      end

      if attributes.key?(:'new_file_name')
        self.new_file_name = attributes[:'new_file_name']
      else
        self.new_file_name = nil
      end

      if attributes.key?(:'old_header')
        self.old_header = attributes[:'old_header']
      end

      if attributes.key?(:'new_header')
        self.new_header = attributes[:'new_header']
      end

      if attributes.key?(:'hunks')
        if (value = attributes[:'hunks']).is_a?(Array)
          self.hunks = value
        end
      else
        self.hunks = nil
      end

      if attributes.key?(:'index')
        self.index = attributes[:'index']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @old_file_name.nil?
        invalid_properties.push('invalid value for "old_file_name", old_file_name cannot be nil.')
      end

      if @new_file_name.nil?
        invalid_properties.push('invalid value for "new_file_name", new_file_name cannot be nil.')
      end

      if @hunks.nil?
        invalid_properties.push('invalid value for "hunks", hunks cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @old_file_name.nil?
      return false if @new_file_name.nil?
      return false if @hunks.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] old_file_name Value to be assigned
    def old_file_name=(old_file_name)
      if old_file_name.nil?
        fail ArgumentError, 'old_file_name cannot be nil'
      end

      @old_file_name = old_file_name
    end

    # Custom attribute writer method with validation
    # @param [Object] new_file_name Value to be assigned
    def new_file_name=(new_file_name)
      if new_file_name.nil?
        fail ArgumentError, 'new_file_name cannot be nil'
      end

      @new_file_name = new_file_name
    end

    # Custom attribute writer method with validation
    # @param [Object] hunks Value to be assigned
    def hunks=(hunks)
      if hunks.nil?
        fail ArgumentError, 'hunks cannot be nil'
      end

      @hunks = hunks
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          old_file_name == o.old_file_name &&
          new_file_name == o.new_file_name &&
          old_header == o.old_header &&
          new_header == o.new_header &&
          hunks == o.hunks &&
          index == o.index
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [old_file_name, new_file_name, old_header, new_header, hunks, index].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
