=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class FileContentPatchHunksInner < ApiModelBase
    attr_accessor :old_start

    attr_accessor :old_lines

    attr_accessor :new_start

    attr_accessor :new_lines

    attr_accessor :lines

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'old_start' => :'oldStart',
        :'old_lines' => :'oldLines',
        :'new_start' => :'newStart',
        :'new_lines' => :'newLines',
        :'lines' => :'lines'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'old_start' => :'Float',
        :'old_lines' => :'Float',
        :'new_start' => :'Float',
        :'new_lines' => :'Float',
        :'lines' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::FileContentPatchHunksInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::FileContentPatchHunksInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'old_start')
        self.old_start = attributes[:'old_start']
      else
        self.old_start = nil
      end

      if attributes.key?(:'old_lines')
        self.old_lines = attributes[:'old_lines']
      else
        self.old_lines = nil
      end

      if attributes.key?(:'new_start')
        self.new_start = attributes[:'new_start']
      else
        self.new_start = nil
      end

      if attributes.key?(:'new_lines')
        self.new_lines = attributes[:'new_lines']
      else
        self.new_lines = nil
      end

      if attributes.key?(:'lines')
        if (value = attributes[:'lines']).is_a?(Array)
          self.lines = value
        end
      else
        self.lines = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @old_start.nil?
        invalid_properties.push('invalid value for "old_start", old_start cannot be nil.')
      end

      if @old_lines.nil?
        invalid_properties.push('invalid value for "old_lines", old_lines cannot be nil.')
      end

      if @new_start.nil?
        invalid_properties.push('invalid value for "new_start", new_start cannot be nil.')
      end

      if @new_lines.nil?
        invalid_properties.push('invalid value for "new_lines", new_lines cannot be nil.')
      end

      if @lines.nil?
        invalid_properties.push('invalid value for "lines", lines cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @old_start.nil?
      return false if @old_lines.nil?
      return false if @new_start.nil?
      return false if @new_lines.nil?
      return false if @lines.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] old_start Value to be assigned
    def old_start=(old_start)
      if old_start.nil?
        fail ArgumentError, 'old_start cannot be nil'
      end

      @old_start = old_start
    end

    # Custom attribute writer method with validation
    # @param [Object] old_lines Value to be assigned
    def old_lines=(old_lines)
      if old_lines.nil?
        fail ArgumentError, 'old_lines cannot be nil'
      end

      @old_lines = old_lines
    end

    # Custom attribute writer method with validation
    # @param [Object] new_start Value to be assigned
    def new_start=(new_start)
      if new_start.nil?
        fail ArgumentError, 'new_start cannot be nil'
      end

      @new_start = new_start
    end

    # Custom attribute writer method with validation
    # @param [Object] new_lines Value to be assigned
    def new_lines=(new_lines)
      if new_lines.nil?
        fail ArgumentError, 'new_lines cannot be nil'
      end

      @new_lines = new_lines
    end

    # Custom attribute writer method with validation
    # @param [Object] lines Value to be assigned
    def lines=(lines)
      if lines.nil?
        fail ArgumentError, 'lines cannot be nil'
      end

      @lines = lines
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          old_start == o.old_start &&
          old_lines == o.old_lines &&
          new_start == o.new_start &&
          new_lines == o.new_lines &&
          lines == o.lines
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [old_start, old_lines, new_start, new_lines, lines].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
