=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class FindText200ResponseInner < ApiModelBase
    attr_accessor :path

    attr_accessor :lines

    attr_accessor :line_number

    attr_accessor :absolute_offset

    attr_accessor :submatches

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'path' => :'path',
        :'lines' => :'lines',
        :'line_number' => :'line_number',
        :'absolute_offset' => :'absolute_offset',
        :'submatches' => :'submatches'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'path' => :'FindText200ResponseInnerPath',
        :'lines' => :'FindText200ResponseInnerPath',
        :'line_number' => :'Float',
        :'absolute_offset' => :'Float',
        :'submatches' => :'Array<FindText200ResponseInnerSubmatchesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::FindText200ResponseInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::FindText200ResponseInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'path')
        self.path = attributes[:'path']
      else
        self.path = nil
      end

      if attributes.key?(:'lines')
        self.lines = attributes[:'lines']
      else
        self.lines = nil
      end

      if attributes.key?(:'line_number')
        self.line_number = attributes[:'line_number']
      else
        self.line_number = nil
      end

      if attributes.key?(:'absolute_offset')
        self.absolute_offset = attributes[:'absolute_offset']
      else
        self.absolute_offset = nil
      end

      if attributes.key?(:'submatches')
        if (value = attributes[:'submatches']).is_a?(Array)
          self.submatches = value
        end
      else
        self.submatches = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @path.nil?
        invalid_properties.push('invalid value for "path", path cannot be nil.')
      end

      if @lines.nil?
        invalid_properties.push('invalid value for "lines", lines cannot be nil.')
      end

      if @line_number.nil?
        invalid_properties.push('invalid value for "line_number", line_number cannot be nil.')
      end

      if @absolute_offset.nil?
        invalid_properties.push('invalid value for "absolute_offset", absolute_offset cannot be nil.')
      end

      if @submatches.nil?
        invalid_properties.push('invalid value for "submatches", submatches cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @path.nil?
      return false if @lines.nil?
      return false if @line_number.nil?
      return false if @absolute_offset.nil?
      return false if @submatches.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] path Value to be assigned
    def path=(path)
      if path.nil?
        fail ArgumentError, 'path cannot be nil'
      end

      @path = path
    end

    # Custom attribute writer method with validation
    # @param [Object] lines Value to be assigned
    def lines=(lines)
      if lines.nil?
        fail ArgumentError, 'lines cannot be nil'
      end

      @lines = lines
    end

    # Custom attribute writer method with validation
    # @param [Object] line_number Value to be assigned
    def line_number=(line_number)
      if line_number.nil?
        fail ArgumentError, 'line_number cannot be nil'
      end

      @line_number = line_number
    end

    # Custom attribute writer method with validation
    # @param [Object] absolute_offset Value to be assigned
    def absolute_offset=(absolute_offset)
      if absolute_offset.nil?
        fail ArgumentError, 'absolute_offset cannot be nil'
      end

      @absolute_offset = absolute_offset
    end

    # Custom attribute writer method with validation
    # @param [Object] submatches Value to be assigned
    def submatches=(submatches)
      if submatches.nil?
        fail ArgumentError, 'submatches cannot be nil'
      end

      @submatches = submatches
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          path == o.path &&
          lines == o.lines &&
          line_number == o.line_number &&
          absolute_offset == o.absolute_offset &&
          submatches == o.submatches
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [path, lines, line_number, absolute_offset, submatches].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
