=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  # Custom keybind configurations
  class KeybindsConfig < ApiModelBase
    # Leader key for keybind combinations
    attr_accessor :leader

    # Exit the application
    attr_accessor :app_exit

    # Open external editor
    attr_accessor :editor_open

    # List available themes
    attr_accessor :theme_list

    # Toggle sidebar
    attr_accessor :sidebar_toggle

    # Toggle session scrollbar
    attr_accessor :scrollbar_toggle

    # Toggle username visibility
    attr_accessor :username_toggle

    # View status
    attr_accessor :status_view

    # Export session to editor
    attr_accessor :session_export

    # Create a new session
    attr_accessor :session_new

    # List all sessions
    attr_accessor :session_list

    # Show session timeline
    attr_accessor :session_timeline

    # Fork session from message
    attr_accessor :session_fork

    # Rename session
    attr_accessor :session_rename

    # Delete session
    attr_accessor :session_delete

    # Delete stash entry
    attr_accessor :stash_delete

    # Open provider list from model dialog
    attr_accessor :model_provider_list

    # Toggle model favorite status
    attr_accessor :model_favorite_toggle

    # Share current session
    attr_accessor :session_share

    # Unshare current session
    attr_accessor :session_unshare

    # Interrupt current session
    attr_accessor :session_interrupt

    # Compact the session
    attr_accessor :session_compact

    # Scroll messages up by one page
    attr_accessor :messages_page_up

    # Scroll messages down by one page
    attr_accessor :messages_page_down

    # Scroll messages up by one line
    attr_accessor :messages_line_up

    # Scroll messages down by one line
    attr_accessor :messages_line_down

    # Scroll messages up by half page
    attr_accessor :messages_half_page_up

    # Scroll messages down by half page
    attr_accessor :messages_half_page_down

    # Navigate to first message
    attr_accessor :messages_first

    # Navigate to last message
    attr_accessor :messages_last

    # Navigate to next message
    attr_accessor :messages_next

    # Navigate to previous message
    attr_accessor :messages_previous

    # Navigate to last user message
    attr_accessor :messages_last_user

    # Copy message
    attr_accessor :messages_copy

    # Undo message
    attr_accessor :messages_undo

    # Redo message
    attr_accessor :messages_redo

    # Toggle code block concealment in messages
    attr_accessor :messages_toggle_conceal

    # Toggle tool details visibility
    attr_accessor :tool_details

    # List available models
    attr_accessor :model_list

    # Next recently used model
    attr_accessor :model_cycle_recent

    # Previous recently used model
    attr_accessor :model_cycle_recent_reverse

    # Next favorite model
    attr_accessor :model_cycle_favorite

    # Previous favorite model
    attr_accessor :model_cycle_favorite_reverse

    # List available commands
    attr_accessor :command_list

    # List agents
    attr_accessor :agent_list

    # Next agent
    attr_accessor :agent_cycle

    # Previous agent
    attr_accessor :agent_cycle_reverse

    # Cycle model variants
    attr_accessor :variant_cycle

    # Clear input field
    attr_accessor :input_clear

    # Paste from clipboard
    attr_accessor :input_paste

    # Submit input
    attr_accessor :input_submit

    # Insert newline in input
    attr_accessor :input_newline

    # Move cursor left in input
    attr_accessor :input_move_left

    # Move cursor right in input
    attr_accessor :input_move_right

    # Move cursor up in input
    attr_accessor :input_move_up

    # Move cursor down in input
    attr_accessor :input_move_down

    # Select left in input
    attr_accessor :input_select_left

    # Select right in input
    attr_accessor :input_select_right

    # Select up in input
    attr_accessor :input_select_up

    # Select down in input
    attr_accessor :input_select_down

    # Move to start of line in input
    attr_accessor :input_line_home

    # Move to end of line in input
    attr_accessor :input_line_end

    # Select to start of line in input
    attr_accessor :input_select_line_home

    # Select to end of line in input
    attr_accessor :input_select_line_end

    # Move to start of visual line in input
    attr_accessor :input_visual_line_home

    # Move to end of visual line in input
    attr_accessor :input_visual_line_end

    # Select to start of visual line in input
    attr_accessor :input_select_visual_line_home

    # Select to end of visual line in input
    attr_accessor :input_select_visual_line_end

    # Move to start of buffer in input
    attr_accessor :input_buffer_home

    # Move to end of buffer in input
    attr_accessor :input_buffer_end

    # Select to start of buffer in input
    attr_accessor :input_select_buffer_home

    # Select to end of buffer in input
    attr_accessor :input_select_buffer_end

    # Delete line in input
    attr_accessor :input_delete_line

    # Delete to end of line in input
    attr_accessor :input_delete_to_line_end

    # Delete to start of line in input
    attr_accessor :input_delete_to_line_start

    # Backspace in input
    attr_accessor :input_backspace

    # Delete character in input
    attr_accessor :input_delete

    # Undo in input
    attr_accessor :input_undo

    # Redo in input
    attr_accessor :input_redo

    # Move word forward in input
    attr_accessor :input_word_forward

    # Move word backward in input
    attr_accessor :input_word_backward

    # Select word forward in input
    attr_accessor :input_select_word_forward

    # Select word backward in input
    attr_accessor :input_select_word_backward

    # Delete word forward in input
    attr_accessor :input_delete_word_forward

    # Delete word backward in input
    attr_accessor :input_delete_word_backward

    # Previous history item
    attr_accessor :history_previous

    # Next history item
    attr_accessor :history_next

    # Next child session
    attr_accessor :session_child_cycle

    # Previous child session
    attr_accessor :session_child_cycle_reverse

    # Go to parent session
    attr_accessor :session_parent

    # Suspend terminal
    attr_accessor :terminal_suspend

    # Toggle terminal title
    attr_accessor :terminal_title_toggle

    # Toggle tips on home screen
    attr_accessor :tips_toggle

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'leader' => :'leader',
        :'app_exit' => :'app_exit',
        :'editor_open' => :'editor_open',
        :'theme_list' => :'theme_list',
        :'sidebar_toggle' => :'sidebar_toggle',
        :'scrollbar_toggle' => :'scrollbar_toggle',
        :'username_toggle' => :'username_toggle',
        :'status_view' => :'status_view',
        :'session_export' => :'session_export',
        :'session_new' => :'session_new',
        :'session_list' => :'session_list',
        :'session_timeline' => :'session_timeline',
        :'session_fork' => :'session_fork',
        :'session_rename' => :'session_rename',
        :'session_delete' => :'session_delete',
        :'stash_delete' => :'stash_delete',
        :'model_provider_list' => :'model_provider_list',
        :'model_favorite_toggle' => :'model_favorite_toggle',
        :'session_share' => :'session_share',
        :'session_unshare' => :'session_unshare',
        :'session_interrupt' => :'session_interrupt',
        :'session_compact' => :'session_compact',
        :'messages_page_up' => :'messages_page_up',
        :'messages_page_down' => :'messages_page_down',
        :'messages_line_up' => :'messages_line_up',
        :'messages_line_down' => :'messages_line_down',
        :'messages_half_page_up' => :'messages_half_page_up',
        :'messages_half_page_down' => :'messages_half_page_down',
        :'messages_first' => :'messages_first',
        :'messages_last' => :'messages_last',
        :'messages_next' => :'messages_next',
        :'messages_previous' => :'messages_previous',
        :'messages_last_user' => :'messages_last_user',
        :'messages_copy' => :'messages_copy',
        :'messages_undo' => :'messages_undo',
        :'messages_redo' => :'messages_redo',
        :'messages_toggle_conceal' => :'messages_toggle_conceal',
        :'tool_details' => :'tool_details',
        :'model_list' => :'model_list',
        :'model_cycle_recent' => :'model_cycle_recent',
        :'model_cycle_recent_reverse' => :'model_cycle_recent_reverse',
        :'model_cycle_favorite' => :'model_cycle_favorite',
        :'model_cycle_favorite_reverse' => :'model_cycle_favorite_reverse',
        :'command_list' => :'command_list',
        :'agent_list' => :'agent_list',
        :'agent_cycle' => :'agent_cycle',
        :'agent_cycle_reverse' => :'agent_cycle_reverse',
        :'variant_cycle' => :'variant_cycle',
        :'input_clear' => :'input_clear',
        :'input_paste' => :'input_paste',
        :'input_submit' => :'input_submit',
        :'input_newline' => :'input_newline',
        :'input_move_left' => :'input_move_left',
        :'input_move_right' => :'input_move_right',
        :'input_move_up' => :'input_move_up',
        :'input_move_down' => :'input_move_down',
        :'input_select_left' => :'input_select_left',
        :'input_select_right' => :'input_select_right',
        :'input_select_up' => :'input_select_up',
        :'input_select_down' => :'input_select_down',
        :'input_line_home' => :'input_line_home',
        :'input_line_end' => :'input_line_end',
        :'input_select_line_home' => :'input_select_line_home',
        :'input_select_line_end' => :'input_select_line_end',
        :'input_visual_line_home' => :'input_visual_line_home',
        :'input_visual_line_end' => :'input_visual_line_end',
        :'input_select_visual_line_home' => :'input_select_visual_line_home',
        :'input_select_visual_line_end' => :'input_select_visual_line_end',
        :'input_buffer_home' => :'input_buffer_home',
        :'input_buffer_end' => :'input_buffer_end',
        :'input_select_buffer_home' => :'input_select_buffer_home',
        :'input_select_buffer_end' => :'input_select_buffer_end',
        :'input_delete_line' => :'input_delete_line',
        :'input_delete_to_line_end' => :'input_delete_to_line_end',
        :'input_delete_to_line_start' => :'input_delete_to_line_start',
        :'input_backspace' => :'input_backspace',
        :'input_delete' => :'input_delete',
        :'input_undo' => :'input_undo',
        :'input_redo' => :'input_redo',
        :'input_word_forward' => :'input_word_forward',
        :'input_word_backward' => :'input_word_backward',
        :'input_select_word_forward' => :'input_select_word_forward',
        :'input_select_word_backward' => :'input_select_word_backward',
        :'input_delete_word_forward' => :'input_delete_word_forward',
        :'input_delete_word_backward' => :'input_delete_word_backward',
        :'history_previous' => :'history_previous',
        :'history_next' => :'history_next',
        :'session_child_cycle' => :'session_child_cycle',
        :'session_child_cycle_reverse' => :'session_child_cycle_reverse',
        :'session_parent' => :'session_parent',
        :'terminal_suspend' => :'terminal_suspend',
        :'terminal_title_toggle' => :'terminal_title_toggle',
        :'tips_toggle' => :'tips_toggle'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'leader' => :'String',
        :'app_exit' => :'String',
        :'editor_open' => :'String',
        :'theme_list' => :'String',
        :'sidebar_toggle' => :'String',
        :'scrollbar_toggle' => :'String',
        :'username_toggle' => :'String',
        :'status_view' => :'String',
        :'session_export' => :'String',
        :'session_new' => :'String',
        :'session_list' => :'String',
        :'session_timeline' => :'String',
        :'session_fork' => :'String',
        :'session_rename' => :'String',
        :'session_delete' => :'String',
        :'stash_delete' => :'String',
        :'model_provider_list' => :'String',
        :'model_favorite_toggle' => :'String',
        :'session_share' => :'String',
        :'session_unshare' => :'String',
        :'session_interrupt' => :'String',
        :'session_compact' => :'String',
        :'messages_page_up' => :'String',
        :'messages_page_down' => :'String',
        :'messages_line_up' => :'String',
        :'messages_line_down' => :'String',
        :'messages_half_page_up' => :'String',
        :'messages_half_page_down' => :'String',
        :'messages_first' => :'String',
        :'messages_last' => :'String',
        :'messages_next' => :'String',
        :'messages_previous' => :'String',
        :'messages_last_user' => :'String',
        :'messages_copy' => :'String',
        :'messages_undo' => :'String',
        :'messages_redo' => :'String',
        :'messages_toggle_conceal' => :'String',
        :'tool_details' => :'String',
        :'model_list' => :'String',
        :'model_cycle_recent' => :'String',
        :'model_cycle_recent_reverse' => :'String',
        :'model_cycle_favorite' => :'String',
        :'model_cycle_favorite_reverse' => :'String',
        :'command_list' => :'String',
        :'agent_list' => :'String',
        :'agent_cycle' => :'String',
        :'agent_cycle_reverse' => :'String',
        :'variant_cycle' => :'String',
        :'input_clear' => :'String',
        :'input_paste' => :'String',
        :'input_submit' => :'String',
        :'input_newline' => :'String',
        :'input_move_left' => :'String',
        :'input_move_right' => :'String',
        :'input_move_up' => :'String',
        :'input_move_down' => :'String',
        :'input_select_left' => :'String',
        :'input_select_right' => :'String',
        :'input_select_up' => :'String',
        :'input_select_down' => :'String',
        :'input_line_home' => :'String',
        :'input_line_end' => :'String',
        :'input_select_line_home' => :'String',
        :'input_select_line_end' => :'String',
        :'input_visual_line_home' => :'String',
        :'input_visual_line_end' => :'String',
        :'input_select_visual_line_home' => :'String',
        :'input_select_visual_line_end' => :'String',
        :'input_buffer_home' => :'String',
        :'input_buffer_end' => :'String',
        :'input_select_buffer_home' => :'String',
        :'input_select_buffer_end' => :'String',
        :'input_delete_line' => :'String',
        :'input_delete_to_line_end' => :'String',
        :'input_delete_to_line_start' => :'String',
        :'input_backspace' => :'String',
        :'input_delete' => :'String',
        :'input_undo' => :'String',
        :'input_redo' => :'String',
        :'input_word_forward' => :'String',
        :'input_word_backward' => :'String',
        :'input_select_word_forward' => :'String',
        :'input_select_word_backward' => :'String',
        :'input_delete_word_forward' => :'String',
        :'input_delete_word_backward' => :'String',
        :'history_previous' => :'String',
        :'history_next' => :'String',
        :'session_child_cycle' => :'String',
        :'session_child_cycle_reverse' => :'String',
        :'session_parent' => :'String',
        :'terminal_suspend' => :'String',
        :'terminal_title_toggle' => :'String',
        :'tips_toggle' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::KeybindsConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::KeybindsConfig`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'leader')
        self.leader = attributes[:'leader']
      else
        self.leader = 'ctrl+x'
      end

      if attributes.key?(:'app_exit')
        self.app_exit = attributes[:'app_exit']
      else
        self.app_exit = 'ctrl+c,ctrl+d,<leader>q'
      end

      if attributes.key?(:'editor_open')
        self.editor_open = attributes[:'editor_open']
      else
        self.editor_open = '<leader>e'
      end

      if attributes.key?(:'theme_list')
        self.theme_list = attributes[:'theme_list']
      else
        self.theme_list = '<leader>t'
      end

      if attributes.key?(:'sidebar_toggle')
        self.sidebar_toggle = attributes[:'sidebar_toggle']
      else
        self.sidebar_toggle = '<leader>b'
      end

      if attributes.key?(:'scrollbar_toggle')
        self.scrollbar_toggle = attributes[:'scrollbar_toggle']
      else
        self.scrollbar_toggle = 'none'
      end

      if attributes.key?(:'username_toggle')
        self.username_toggle = attributes[:'username_toggle']
      else
        self.username_toggle = 'none'
      end

      if attributes.key?(:'status_view')
        self.status_view = attributes[:'status_view']
      else
        self.status_view = '<leader>s'
      end

      if attributes.key?(:'session_export')
        self.session_export = attributes[:'session_export']
      else
        self.session_export = '<leader>x'
      end

      if attributes.key?(:'session_new')
        self.session_new = attributes[:'session_new']
      else
        self.session_new = '<leader>n'
      end

      if attributes.key?(:'session_list')
        self.session_list = attributes[:'session_list']
      else
        self.session_list = '<leader>l'
      end

      if attributes.key?(:'session_timeline')
        self.session_timeline = attributes[:'session_timeline']
      else
        self.session_timeline = '<leader>g'
      end

      if attributes.key?(:'session_fork')
        self.session_fork = attributes[:'session_fork']
      else
        self.session_fork = 'none'
      end

      if attributes.key?(:'session_rename')
        self.session_rename = attributes[:'session_rename']
      else
        self.session_rename = 'ctrl+r'
      end

      if attributes.key?(:'session_delete')
        self.session_delete = attributes[:'session_delete']
      else
        self.session_delete = 'ctrl+d'
      end

      if attributes.key?(:'stash_delete')
        self.stash_delete = attributes[:'stash_delete']
      else
        self.stash_delete = 'ctrl+d'
      end

      if attributes.key?(:'model_provider_list')
        self.model_provider_list = attributes[:'model_provider_list']
      else
        self.model_provider_list = 'ctrl+a'
      end

      if attributes.key?(:'model_favorite_toggle')
        self.model_favorite_toggle = attributes[:'model_favorite_toggle']
      else
        self.model_favorite_toggle = 'ctrl+f'
      end

      if attributes.key?(:'session_share')
        self.session_share = attributes[:'session_share']
      else
        self.session_share = 'none'
      end

      if attributes.key?(:'session_unshare')
        self.session_unshare = attributes[:'session_unshare']
      else
        self.session_unshare = 'none'
      end

      if attributes.key?(:'session_interrupt')
        self.session_interrupt = attributes[:'session_interrupt']
      else
        self.session_interrupt = 'escape'
      end

      if attributes.key?(:'session_compact')
        self.session_compact = attributes[:'session_compact']
      else
        self.session_compact = '<leader>c'
      end

      if attributes.key?(:'messages_page_up')
        self.messages_page_up = attributes[:'messages_page_up']
      else
        self.messages_page_up = 'pageup,ctrl+alt+b'
      end

      if attributes.key?(:'messages_page_down')
        self.messages_page_down = attributes[:'messages_page_down']
      else
        self.messages_page_down = 'pagedown,ctrl+alt+f'
      end

      if attributes.key?(:'messages_line_up')
        self.messages_line_up = attributes[:'messages_line_up']
      else
        self.messages_line_up = 'ctrl+alt+y'
      end

      if attributes.key?(:'messages_line_down')
        self.messages_line_down = attributes[:'messages_line_down']
      else
        self.messages_line_down = 'ctrl+alt+e'
      end

      if attributes.key?(:'messages_half_page_up')
        self.messages_half_page_up = attributes[:'messages_half_page_up']
      else
        self.messages_half_page_up = 'ctrl+alt+u'
      end

      if attributes.key?(:'messages_half_page_down')
        self.messages_half_page_down = attributes[:'messages_half_page_down']
      else
        self.messages_half_page_down = 'ctrl+alt+d'
      end

      if attributes.key?(:'messages_first')
        self.messages_first = attributes[:'messages_first']
      else
        self.messages_first = 'ctrl+g,home'
      end

      if attributes.key?(:'messages_last')
        self.messages_last = attributes[:'messages_last']
      else
        self.messages_last = 'ctrl+alt+g,end'
      end

      if attributes.key?(:'messages_next')
        self.messages_next = attributes[:'messages_next']
      else
        self.messages_next = 'none'
      end

      if attributes.key?(:'messages_previous')
        self.messages_previous = attributes[:'messages_previous']
      else
        self.messages_previous = 'none'
      end

      if attributes.key?(:'messages_last_user')
        self.messages_last_user = attributes[:'messages_last_user']
      else
        self.messages_last_user = 'none'
      end

      if attributes.key?(:'messages_copy')
        self.messages_copy = attributes[:'messages_copy']
      else
        self.messages_copy = '<leader>y'
      end

      if attributes.key?(:'messages_undo')
        self.messages_undo = attributes[:'messages_undo']
      else
        self.messages_undo = '<leader>u'
      end

      if attributes.key?(:'messages_redo')
        self.messages_redo = attributes[:'messages_redo']
      else
        self.messages_redo = '<leader>r'
      end

      if attributes.key?(:'messages_toggle_conceal')
        self.messages_toggle_conceal = attributes[:'messages_toggle_conceal']
      else
        self.messages_toggle_conceal = '<leader>h'
      end

      if attributes.key?(:'tool_details')
        self.tool_details = attributes[:'tool_details']
      else
        self.tool_details = 'none'
      end

      if attributes.key?(:'model_list')
        self.model_list = attributes[:'model_list']
      else
        self.model_list = '<leader>m'
      end

      if attributes.key?(:'model_cycle_recent')
        self.model_cycle_recent = attributes[:'model_cycle_recent']
      else
        self.model_cycle_recent = 'f2'
      end

      if attributes.key?(:'model_cycle_recent_reverse')
        self.model_cycle_recent_reverse = attributes[:'model_cycle_recent_reverse']
      else
        self.model_cycle_recent_reverse = 'shift+f2'
      end

      if attributes.key?(:'model_cycle_favorite')
        self.model_cycle_favorite = attributes[:'model_cycle_favorite']
      else
        self.model_cycle_favorite = 'none'
      end

      if attributes.key?(:'model_cycle_favorite_reverse')
        self.model_cycle_favorite_reverse = attributes[:'model_cycle_favorite_reverse']
      else
        self.model_cycle_favorite_reverse = 'none'
      end

      if attributes.key?(:'command_list')
        self.command_list = attributes[:'command_list']
      else
        self.command_list = 'ctrl+p'
      end

      if attributes.key?(:'agent_list')
        self.agent_list = attributes[:'agent_list']
      else
        self.agent_list = '<leader>a'
      end

      if attributes.key?(:'agent_cycle')
        self.agent_cycle = attributes[:'agent_cycle']
      else
        self.agent_cycle = 'tab'
      end

      if attributes.key?(:'agent_cycle_reverse')
        self.agent_cycle_reverse = attributes[:'agent_cycle_reverse']
      else
        self.agent_cycle_reverse = 'shift+tab'
      end

      if attributes.key?(:'variant_cycle')
        self.variant_cycle = attributes[:'variant_cycle']
      else
        self.variant_cycle = 'ctrl+t'
      end

      if attributes.key?(:'input_clear')
        self.input_clear = attributes[:'input_clear']
      else
        self.input_clear = 'ctrl+c'
      end

      if attributes.key?(:'input_paste')
        self.input_paste = attributes[:'input_paste']
      else
        self.input_paste = 'ctrl+v'
      end

      if attributes.key?(:'input_submit')
        self.input_submit = attributes[:'input_submit']
      else
        self.input_submit = 'return'
      end

      if attributes.key?(:'input_newline')
        self.input_newline = attributes[:'input_newline']
      else
        self.input_newline = 'shift+return,ctrl+return,alt+return,ctrl+j'
      end

      if attributes.key?(:'input_move_left')
        self.input_move_left = attributes[:'input_move_left']
      else
        self.input_move_left = 'left,ctrl+b'
      end

      if attributes.key?(:'input_move_right')
        self.input_move_right = attributes[:'input_move_right']
      else
        self.input_move_right = 'right,ctrl+f'
      end

      if attributes.key?(:'input_move_up')
        self.input_move_up = attributes[:'input_move_up']
      else
        self.input_move_up = 'up'
      end

      if attributes.key?(:'input_move_down')
        self.input_move_down = attributes[:'input_move_down']
      else
        self.input_move_down = 'down'
      end

      if attributes.key?(:'input_select_left')
        self.input_select_left = attributes[:'input_select_left']
      else
        self.input_select_left = 'shift+left'
      end

      if attributes.key?(:'input_select_right')
        self.input_select_right = attributes[:'input_select_right']
      else
        self.input_select_right = 'shift+right'
      end

      if attributes.key?(:'input_select_up')
        self.input_select_up = attributes[:'input_select_up']
      else
        self.input_select_up = 'shift+up'
      end

      if attributes.key?(:'input_select_down')
        self.input_select_down = attributes[:'input_select_down']
      else
        self.input_select_down = 'shift+down'
      end

      if attributes.key?(:'input_line_home')
        self.input_line_home = attributes[:'input_line_home']
      else
        self.input_line_home = 'ctrl+a'
      end

      if attributes.key?(:'input_line_end')
        self.input_line_end = attributes[:'input_line_end']
      else
        self.input_line_end = 'ctrl+e'
      end

      if attributes.key?(:'input_select_line_home')
        self.input_select_line_home = attributes[:'input_select_line_home']
      else
        self.input_select_line_home = 'ctrl+shift+a'
      end

      if attributes.key?(:'input_select_line_end')
        self.input_select_line_end = attributes[:'input_select_line_end']
      else
        self.input_select_line_end = 'ctrl+shift+e'
      end

      if attributes.key?(:'input_visual_line_home')
        self.input_visual_line_home = attributes[:'input_visual_line_home']
      else
        self.input_visual_line_home = 'alt+a'
      end

      if attributes.key?(:'input_visual_line_end')
        self.input_visual_line_end = attributes[:'input_visual_line_end']
      else
        self.input_visual_line_end = 'alt+e'
      end

      if attributes.key?(:'input_select_visual_line_home')
        self.input_select_visual_line_home = attributes[:'input_select_visual_line_home']
      else
        self.input_select_visual_line_home = 'alt+shift+a'
      end

      if attributes.key?(:'input_select_visual_line_end')
        self.input_select_visual_line_end = attributes[:'input_select_visual_line_end']
      else
        self.input_select_visual_line_end = 'alt+shift+e'
      end

      if attributes.key?(:'input_buffer_home')
        self.input_buffer_home = attributes[:'input_buffer_home']
      else
        self.input_buffer_home = 'home'
      end

      if attributes.key?(:'input_buffer_end')
        self.input_buffer_end = attributes[:'input_buffer_end']
      else
        self.input_buffer_end = 'end'
      end

      if attributes.key?(:'input_select_buffer_home')
        self.input_select_buffer_home = attributes[:'input_select_buffer_home']
      else
        self.input_select_buffer_home = 'shift+home'
      end

      if attributes.key?(:'input_select_buffer_end')
        self.input_select_buffer_end = attributes[:'input_select_buffer_end']
      else
        self.input_select_buffer_end = 'shift+end'
      end

      if attributes.key?(:'input_delete_line')
        self.input_delete_line = attributes[:'input_delete_line']
      else
        self.input_delete_line = 'ctrl+shift+d'
      end

      if attributes.key?(:'input_delete_to_line_end')
        self.input_delete_to_line_end = attributes[:'input_delete_to_line_end']
      else
        self.input_delete_to_line_end = 'ctrl+k'
      end

      if attributes.key?(:'input_delete_to_line_start')
        self.input_delete_to_line_start = attributes[:'input_delete_to_line_start']
      else
        self.input_delete_to_line_start = 'ctrl+u'
      end

      if attributes.key?(:'input_backspace')
        self.input_backspace = attributes[:'input_backspace']
      else
        self.input_backspace = 'backspace,shift+backspace'
      end

      if attributes.key?(:'input_delete')
        self.input_delete = attributes[:'input_delete']
      else
        self.input_delete = 'ctrl+d,delete,shift+delete'
      end

      if attributes.key?(:'input_undo')
        self.input_undo = attributes[:'input_undo']
      else
        self.input_undo = 'ctrl+-,super+z'
      end

      if attributes.key?(:'input_redo')
        self.input_redo = attributes[:'input_redo']
      else
        self.input_redo = 'ctrl+.,super+shift+z'
      end

      if attributes.key?(:'input_word_forward')
        self.input_word_forward = attributes[:'input_word_forward']
      else
        self.input_word_forward = 'alt+f,alt+right,ctrl+right'
      end

      if attributes.key?(:'input_word_backward')
        self.input_word_backward = attributes[:'input_word_backward']
      else
        self.input_word_backward = 'alt+b,alt+left,ctrl+left'
      end

      if attributes.key?(:'input_select_word_forward')
        self.input_select_word_forward = attributes[:'input_select_word_forward']
      else
        self.input_select_word_forward = 'alt+shift+f,alt+shift+right'
      end

      if attributes.key?(:'input_select_word_backward')
        self.input_select_word_backward = attributes[:'input_select_word_backward']
      else
        self.input_select_word_backward = 'alt+shift+b,alt+shift+left'
      end

      if attributes.key?(:'input_delete_word_forward')
        self.input_delete_word_forward = attributes[:'input_delete_word_forward']
      else
        self.input_delete_word_forward = 'alt+d,alt+delete,ctrl+delete'
      end

      if attributes.key?(:'input_delete_word_backward')
        self.input_delete_word_backward = attributes[:'input_delete_word_backward']
      else
        self.input_delete_word_backward = 'ctrl+w,ctrl+backspace,alt+backspace'
      end

      if attributes.key?(:'history_previous')
        self.history_previous = attributes[:'history_previous']
      else
        self.history_previous = 'up'
      end

      if attributes.key?(:'history_next')
        self.history_next = attributes[:'history_next']
      else
        self.history_next = 'down'
      end

      if attributes.key?(:'session_child_cycle')
        self.session_child_cycle = attributes[:'session_child_cycle']
      else
        self.session_child_cycle = '<leader>right'
      end

      if attributes.key?(:'session_child_cycle_reverse')
        self.session_child_cycle_reverse = attributes[:'session_child_cycle_reverse']
      else
        self.session_child_cycle_reverse = '<leader>left'
      end

      if attributes.key?(:'session_parent')
        self.session_parent = attributes[:'session_parent']
      else
        self.session_parent = '<leader>up'
      end

      if attributes.key?(:'terminal_suspend')
        self.terminal_suspend = attributes[:'terminal_suspend']
      else
        self.terminal_suspend = 'ctrl+z'
      end

      if attributes.key?(:'terminal_title_toggle')
        self.terminal_title_toggle = attributes[:'terminal_title_toggle']
      else
        self.terminal_title_toggle = 'none'
      end

      if attributes.key?(:'tips_toggle')
        self.tips_toggle = attributes[:'tips_toggle']
      else
        self.tips_toggle = '<leader>h'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          leader == o.leader &&
          app_exit == o.app_exit &&
          editor_open == o.editor_open &&
          theme_list == o.theme_list &&
          sidebar_toggle == o.sidebar_toggle &&
          scrollbar_toggle == o.scrollbar_toggle &&
          username_toggle == o.username_toggle &&
          status_view == o.status_view &&
          session_export == o.session_export &&
          session_new == o.session_new &&
          session_list == o.session_list &&
          session_timeline == o.session_timeline &&
          session_fork == o.session_fork &&
          session_rename == o.session_rename &&
          session_delete == o.session_delete &&
          stash_delete == o.stash_delete &&
          model_provider_list == o.model_provider_list &&
          model_favorite_toggle == o.model_favorite_toggle &&
          session_share == o.session_share &&
          session_unshare == o.session_unshare &&
          session_interrupt == o.session_interrupt &&
          session_compact == o.session_compact &&
          messages_page_up == o.messages_page_up &&
          messages_page_down == o.messages_page_down &&
          messages_line_up == o.messages_line_up &&
          messages_line_down == o.messages_line_down &&
          messages_half_page_up == o.messages_half_page_up &&
          messages_half_page_down == o.messages_half_page_down &&
          messages_first == o.messages_first &&
          messages_last == o.messages_last &&
          messages_next == o.messages_next &&
          messages_previous == o.messages_previous &&
          messages_last_user == o.messages_last_user &&
          messages_copy == o.messages_copy &&
          messages_undo == o.messages_undo &&
          messages_redo == o.messages_redo &&
          messages_toggle_conceal == o.messages_toggle_conceal &&
          tool_details == o.tool_details &&
          model_list == o.model_list &&
          model_cycle_recent == o.model_cycle_recent &&
          model_cycle_recent_reverse == o.model_cycle_recent_reverse &&
          model_cycle_favorite == o.model_cycle_favorite &&
          model_cycle_favorite_reverse == o.model_cycle_favorite_reverse &&
          command_list == o.command_list &&
          agent_list == o.agent_list &&
          agent_cycle == o.agent_cycle &&
          agent_cycle_reverse == o.agent_cycle_reverse &&
          variant_cycle == o.variant_cycle &&
          input_clear == o.input_clear &&
          input_paste == o.input_paste &&
          input_submit == o.input_submit &&
          input_newline == o.input_newline &&
          input_move_left == o.input_move_left &&
          input_move_right == o.input_move_right &&
          input_move_up == o.input_move_up &&
          input_move_down == o.input_move_down &&
          input_select_left == o.input_select_left &&
          input_select_right == o.input_select_right &&
          input_select_up == o.input_select_up &&
          input_select_down == o.input_select_down &&
          input_line_home == o.input_line_home &&
          input_line_end == o.input_line_end &&
          input_select_line_home == o.input_select_line_home &&
          input_select_line_end == o.input_select_line_end &&
          input_visual_line_home == o.input_visual_line_home &&
          input_visual_line_end == o.input_visual_line_end &&
          input_select_visual_line_home == o.input_select_visual_line_home &&
          input_select_visual_line_end == o.input_select_visual_line_end &&
          input_buffer_home == o.input_buffer_home &&
          input_buffer_end == o.input_buffer_end &&
          input_select_buffer_home == o.input_select_buffer_home &&
          input_select_buffer_end == o.input_select_buffer_end &&
          input_delete_line == o.input_delete_line &&
          input_delete_to_line_end == o.input_delete_to_line_end &&
          input_delete_to_line_start == o.input_delete_to_line_start &&
          input_backspace == o.input_backspace &&
          input_delete == o.input_delete &&
          input_undo == o.input_undo &&
          input_redo == o.input_redo &&
          input_word_forward == o.input_word_forward &&
          input_word_backward == o.input_word_backward &&
          input_select_word_forward == o.input_select_word_forward &&
          input_select_word_backward == o.input_select_word_backward &&
          input_delete_word_forward == o.input_delete_word_forward &&
          input_delete_word_backward == o.input_delete_word_backward &&
          history_previous == o.history_previous &&
          history_next == o.history_next &&
          session_child_cycle == o.session_child_cycle &&
          session_child_cycle_reverse == o.session_child_cycle_reverse &&
          session_parent == o.session_parent &&
          terminal_suspend == o.terminal_suspend &&
          terminal_title_toggle == o.terminal_title_toggle &&
          tips_toggle == o.tips_toggle
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [leader, app_exit, editor_open, theme_list, sidebar_toggle, scrollbar_toggle, username_toggle, status_view, session_export, session_new, session_list, session_timeline, session_fork, session_rename, session_delete, stash_delete, model_provider_list, model_favorite_toggle, session_share, session_unshare, session_interrupt, session_compact, messages_page_up, messages_page_down, messages_line_up, messages_line_down, messages_half_page_up, messages_half_page_down, messages_first, messages_last, messages_next, messages_previous, messages_last_user, messages_copy, messages_undo, messages_redo, messages_toggle_conceal, tool_details, model_list, model_cycle_recent, model_cycle_recent_reverse, model_cycle_favorite, model_cycle_favorite_reverse, command_list, agent_list, agent_cycle, agent_cycle_reverse, variant_cycle, input_clear, input_paste, input_submit, input_newline, input_move_left, input_move_right, input_move_up, input_move_down, input_select_left, input_select_right, input_select_up, input_select_down, input_line_home, input_line_end, input_select_line_home, input_select_line_end, input_visual_line_home, input_visual_line_end, input_select_visual_line_home, input_select_visual_line_end, input_buffer_home, input_buffer_end, input_select_buffer_home, input_select_buffer_end, input_delete_line, input_delete_to_line_end, input_delete_to_line_start, input_backspace, input_delete, input_undo, input_redo, input_word_forward, input_word_backward, input_select_word_forward, input_select_word_backward, input_delete_word_forward, input_delete_word_backward, history_previous, history_next, session_child_cycle, session_child_cycle_reverse, session_parent, terminal_suspend, terminal_title_toggle, tips_toggle].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
