=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class LayoutConfig
    AUTO = "auto".freeze
    STRETCH = "stretch".freeze

    def self.all_vars
      @all_vars ||= [AUTO, STRETCH].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if LayoutConfig.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #LayoutConfig"
    end
  end
end
