=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class Model < ApiModelBase
    attr_accessor :id

    attr_accessor :provider_id

    attr_accessor :api

    attr_accessor :name

    attr_accessor :family

    attr_accessor :capabilities

    attr_accessor :cost

    attr_accessor :limit

    attr_accessor :status

    attr_accessor :options

    attr_accessor :headers

    attr_accessor :release_date

    attr_accessor :variants

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'provider_id' => :'providerID',
        :'api' => :'api',
        :'name' => :'name',
        :'family' => :'family',
        :'capabilities' => :'capabilities',
        :'cost' => :'cost',
        :'limit' => :'limit',
        :'status' => :'status',
        :'options' => :'options',
        :'headers' => :'headers',
        :'release_date' => :'release_date',
        :'variants' => :'variants'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'provider_id' => :'String',
        :'api' => :'ModelApi',
        :'name' => :'String',
        :'family' => :'String',
        :'capabilities' => :'ModelCapabilities',
        :'cost' => :'ModelCost',
        :'limit' => :'ProviderList200ResponseAllInnerModelsValueLimit',
        :'status' => :'String',
        :'options' => :'Hash<String, Object>',
        :'headers' => :'Hash<String, String>',
        :'release_date' => :'String',
        :'variants' => :'Hash<String, Hash<String, Object>>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::Model` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::Model`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'provider_id')
        self.provider_id = attributes[:'provider_id']
      else
        self.provider_id = nil
      end

      if attributes.key?(:'api')
        self.api = attributes[:'api']
      else
        self.api = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'family')
        self.family = attributes[:'family']
      end

      if attributes.key?(:'capabilities')
        self.capabilities = attributes[:'capabilities']
      else
        self.capabilities = nil
      end

      if attributes.key?(:'cost')
        self.cost = attributes[:'cost']
      else
        self.cost = nil
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      else
        self.limit = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Hash)
          self.options = value
        end
      else
        self.options = nil
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Hash)
          self.headers = value
        end
      else
        self.headers = nil
      end

      if attributes.key?(:'release_date')
        self.release_date = attributes[:'release_date']
      else
        self.release_date = nil
      end

      if attributes.key?(:'variants')
        if (value = attributes[:'variants']).is_a?(Hash)
          self.variants = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @provider_id.nil?
        invalid_properties.push('invalid value for "provider_id", provider_id cannot be nil.')
      end

      if @api.nil?
        invalid_properties.push('invalid value for "api", api cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @capabilities.nil?
        invalid_properties.push('invalid value for "capabilities", capabilities cannot be nil.')
      end

      if @cost.nil?
        invalid_properties.push('invalid value for "cost", cost cannot be nil.')
      end

      if @limit.nil?
        invalid_properties.push('invalid value for "limit", limit cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @options.nil?
        invalid_properties.push('invalid value for "options", options cannot be nil.')
      end

      if @headers.nil?
        invalid_properties.push('invalid value for "headers", headers cannot be nil.')
      end

      if @release_date.nil?
        invalid_properties.push('invalid value for "release_date", release_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @provider_id.nil?
      return false if @api.nil?
      return false if @name.nil?
      return false if @capabilities.nil?
      return false if @cost.nil?
      return false if @limit.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["alpha", "beta", "deprecated", "active"])
      return false unless status_validator.valid?(@status)
      return false if @options.nil?
      return false if @headers.nil?
      return false if @release_date.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] provider_id Value to be assigned
    def provider_id=(provider_id)
      if provider_id.nil?
        fail ArgumentError, 'provider_id cannot be nil'
      end

      @provider_id = provider_id
    end

    # Custom attribute writer method with validation
    # @param [Object] api Value to be assigned
    def api=(api)
      if api.nil?
        fail ArgumentError, 'api cannot be nil'
      end

      @api = api
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] capabilities Value to be assigned
    def capabilities=(capabilities)
      if capabilities.nil?
        fail ArgumentError, 'capabilities cannot be nil'
      end

      @capabilities = capabilities
    end

    # Custom attribute writer method with validation
    # @param [Object] cost Value to be assigned
    def cost=(cost)
      if cost.nil?
        fail ArgumentError, 'cost cannot be nil'
      end

      @cost = cost
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)
      if limit.nil?
        fail ArgumentError, 'limit cannot be nil'
      end

      @limit = limit
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["alpha", "beta", "deprecated", "active"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] options Value to be assigned
    def options=(options)
      if options.nil?
        fail ArgumentError, 'options cannot be nil'
      end

      @options = options
    end

    # Custom attribute writer method with validation
    # @param [Object] headers Value to be assigned
    def headers=(headers)
      if headers.nil?
        fail ArgumentError, 'headers cannot be nil'
      end

      @headers = headers
    end

    # Custom attribute writer method with validation
    # @param [Object] release_date Value to be assigned
    def release_date=(release_date)
      if release_date.nil?
        fail ArgumentError, 'release_date cannot be nil'
      end

      @release_date = release_date
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          provider_id == o.provider_id &&
          api == o.api &&
          name == o.name &&
          family == o.family &&
          capabilities == o.capabilities &&
          cost == o.cost &&
          limit == o.limit &&
          status == o.status &&
          options == o.options &&
          headers == o.headers &&
          release_date == o.release_date &&
          variants == o.variants
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, provider_id, api, name, family, capabilities, cost, limit, status, options, headers, release_date, variants].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
