=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class ProviderConfigModelsValue < ApiModelBase
    attr_accessor :id

    attr_accessor :name

    attr_accessor :family

    attr_accessor :release_date

    attr_accessor :attachment

    attr_accessor :reasoning

    attr_accessor :temperature

    attr_accessor :tool_call

    attr_accessor :interleaved

    attr_accessor :cost

    attr_accessor :limit

    attr_accessor :modalities

    attr_accessor :experimental

    attr_accessor :status

    attr_accessor :options

    attr_accessor :headers

    attr_accessor :provider

    # Variant-specific configuration
    attr_accessor :variants

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'family' => :'family',
        :'release_date' => :'release_date',
        :'attachment' => :'attachment',
        :'reasoning' => :'reasoning',
        :'temperature' => :'temperature',
        :'tool_call' => :'tool_call',
        :'interleaved' => :'interleaved',
        :'cost' => :'cost',
        :'limit' => :'limit',
        :'modalities' => :'modalities',
        :'experimental' => :'experimental',
        :'status' => :'status',
        :'options' => :'options',
        :'headers' => :'headers',
        :'provider' => :'provider',
        :'variants' => :'variants'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'family' => :'String',
        :'release_date' => :'String',
        :'attachment' => :'Boolean',
        :'reasoning' => :'Boolean',
        :'temperature' => :'Boolean',
        :'tool_call' => :'Boolean',
        :'interleaved' => :'ProviderConfigModelsValueInterleaved',
        :'cost' => :'ProviderList200ResponseAllInnerModelsValueCost',
        :'limit' => :'ProviderList200ResponseAllInnerModelsValueLimit',
        :'modalities' => :'ProviderList200ResponseAllInnerModelsValueModalities',
        :'experimental' => :'Boolean',
        :'status' => :'String',
        :'options' => :'Hash<String, Object>',
        :'headers' => :'Hash<String, String>',
        :'provider' => :'ProviderList200ResponseAllInnerModelsValueProvider',
        :'variants' => :'Hash<String, ProviderConfigModelsValueVariantsValue>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::ProviderConfigModelsValue` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::ProviderConfigModelsValue`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'family')
        self.family = attributes[:'family']
      end

      if attributes.key?(:'release_date')
        self.release_date = attributes[:'release_date']
      end

      if attributes.key?(:'attachment')
        self.attachment = attributes[:'attachment']
      end

      if attributes.key?(:'reasoning')
        self.reasoning = attributes[:'reasoning']
      end

      if attributes.key?(:'temperature')
        self.temperature = attributes[:'temperature']
      end

      if attributes.key?(:'tool_call')
        self.tool_call = attributes[:'tool_call']
      end

      if attributes.key?(:'interleaved')
        self.interleaved = attributes[:'interleaved']
      end

      if attributes.key?(:'cost')
        self.cost = attributes[:'cost']
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      end

      if attributes.key?(:'modalities')
        self.modalities = attributes[:'modalities']
      end

      if attributes.key?(:'experimental')
        self.experimental = attributes[:'experimental']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Hash)
          self.options = value
        end
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Hash)
          self.headers = value
        end
      end

      if attributes.key?(:'provider')
        self.provider = attributes[:'provider']
      end

      if attributes.key?(:'variants')
        if (value = attributes[:'variants']).is_a?(Hash)
          self.variants = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      status_validator = EnumAttributeValidator.new('String', ["alpha", "beta", "deprecated"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["alpha", "beta", "deprecated"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          family == o.family &&
          release_date == o.release_date &&
          attachment == o.attachment &&
          reasoning == o.reasoning &&
          temperature == o.temperature &&
          tool_call == o.tool_call &&
          interleaved == o.interleaved &&
          cost == o.cost &&
          limit == o.limit &&
          modalities == o.modalities &&
          experimental == o.experimental &&
          status == o.status &&
          options == o.options &&
          headers == o.headers &&
          provider == o.provider &&
          variants == o.variants
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, family, release_date, attachment, reasoning, temperature, tool_call, interleaved, cost, limit, modalities, experimental, status, options, headers, provider, variants].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
