=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class QuestionInfo < ApiModelBase
    # Complete question
    attr_accessor :question

    # Very short label (max 30 chars)
    attr_accessor :header

    # Available choices
    attr_accessor :options

    # Allow selecting multiple choices
    attr_accessor :multiple

    # Allow typing a custom answer (default: true)
    attr_accessor :custom

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'question' => :'question',
        :'header' => :'header',
        :'options' => :'options',
        :'multiple' => :'multiple',
        :'custom' => :'custom'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'question' => :'String',
        :'header' => :'String',
        :'options' => :'Array<QuestionOption>',
        :'multiple' => :'Boolean',
        :'custom' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::QuestionInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::QuestionInfo`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'question')
        self.question = attributes[:'question']
      else
        self.question = nil
      end

      if attributes.key?(:'header')
        self.header = attributes[:'header']
      else
        self.header = nil
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Array)
          self.options = value
        end
      else
        self.options = nil
      end

      if attributes.key?(:'multiple')
        self.multiple = attributes[:'multiple']
      end

      if attributes.key?(:'custom')
        self.custom = attributes[:'custom']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @question.nil?
        invalid_properties.push('invalid value for "question", question cannot be nil.')
      end

      if @header.nil?
        invalid_properties.push('invalid value for "header", header cannot be nil.')
      end

      if @header.to_s.length > 30
        invalid_properties.push('invalid value for "header", the character length must be smaller than or equal to 30.')
      end

      if @options.nil?
        invalid_properties.push('invalid value for "options", options cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @question.nil?
      return false if @header.nil?
      return false if @header.to_s.length > 30
      return false if @options.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] question Value to be assigned
    def question=(question)
      if question.nil?
        fail ArgumentError, 'question cannot be nil'
      end

      @question = question
    end

    # Custom attribute writer method with validation
    # @param [Object] header Value to be assigned
    def header=(header)
      if header.nil?
        fail ArgumentError, 'header cannot be nil'
      end

      if header.to_s.length > 30
        fail ArgumentError, 'invalid value for "header", the character length must be smaller than or equal to 30.'
      end

      @header = header
    end

    # Custom attribute writer method with validation
    # @param [Object] options Value to be assigned
    def options=(options)
      if options.nil?
        fail ArgumentError, 'options cannot be nil'
      end

      @options = options
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          question == o.question &&
          header == o.header &&
          options == o.options &&
          multiple == o.multiple &&
          custom == o.custom
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [question, header, options, multiple, custom].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
