=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module OpencodeClient
  class SessionCommandRequest < ApiModelBase
    attr_accessor :message_id

    attr_accessor :agent

    attr_accessor :model

    attr_accessor :arguments

    attr_accessor :command

    attr_accessor :variant

    attr_accessor :parts

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'message_id' => :'messageID',
        :'agent' => :'agent',
        :'model' => :'model',
        :'arguments' => :'arguments',
        :'command' => :'command',
        :'variant' => :'variant',
        :'parts' => :'parts'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'message_id' => :'String',
        :'agent' => :'String',
        :'model' => :'String',
        :'arguments' => :'String',
        :'command' => :'String',
        :'variant' => :'String',
        :'parts' => :'Array<SessionCommandRequestPartsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::SessionCommandRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::SessionCommandRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'message_id')
        self.message_id = attributes[:'message_id']
      end

      if attributes.key?(:'agent')
        self.agent = attributes[:'agent']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'arguments')
        self.arguments = attributes[:'arguments']
      else
        self.arguments = nil
      end

      if attributes.key?(:'command')
        self.command = attributes[:'command']
      else
        self.command = nil
      end

      if attributes.key?(:'variant')
        self.variant = attributes[:'variant']
      end

      if attributes.key?(:'parts')
        if (value = attributes[:'parts']).is_a?(Array)
          self.parts = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^msg.*/)
      if !@message_id.nil? && @message_id !~ pattern
        invalid_properties.push("invalid value for \"message_id\", must conform to the pattern #{pattern}.")
      end

      if @arguments.nil?
        invalid_properties.push('invalid value for "arguments", arguments cannot be nil.')
      end

      if @command.nil?
        invalid_properties.push('invalid value for "command", command cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@message_id.nil? && @message_id !~ Regexp.new(/^msg.*/)
      return false if @arguments.nil?
      return false if @command.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] message_id Value to be assigned
    def message_id=(message_id)
      if message_id.nil?
        fail ArgumentError, 'message_id cannot be nil'
      end

      pattern = Regexp.new(/^msg.*/)
      if message_id !~ pattern
        fail ArgumentError, "invalid value for \"message_id\", must conform to the pattern #{pattern}."
      end

      @message_id = message_id
    end

    # Custom attribute writer method with validation
    # @param [Object] arguments Value to be assigned
    def arguments=(arguments)
      if arguments.nil?
        fail ArgumentError, 'arguments cannot be nil'
      end

      @arguments = arguments
    end

    # Custom attribute writer method with validation
    # @param [Object] command Value to be assigned
    def command=(command)
      if command.nil?
        fail ArgumentError, 'command cannot be nil'
      end

      @command = command
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          message_id == o.message_id &&
          agent == o.agent &&
          model == o.model &&
          arguments == o.arguments &&
          command == o.command &&
          variant == o.variant &&
          parts == o.parts
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [message_id, agent, model, arguments, command, variant, parts].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
