=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpencodeClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpencodeClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpencodeClient::DefaultApi)
    end
  end

  # unit tests for app_agents
  # List agents
  # Get a list of all available AI agents in the OpenCode system.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<Agent>]
  describe 'app_agents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for app_log
  # Write log
  # Write a log entry to the server logs with specified level and metadata.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [AppLogRequest] :app_log_request 
  # @return [Boolean]
  describe 'app_log test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for app_skills
  # List skills
  # Get a list of all available skills in the OpenCode system.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<AppSkills200ResponseInner>]
  describe 'app_skills test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for auth_set
  # Set auth credentials
  # Set authentication credentials
  # @param provider_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [Auth] :auth 
  # @return [Boolean]
  describe 'auth_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for command_list
  # List commands
  # Get a list of all available commands in the OpenCode system.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<Command>]
  describe 'command_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for config_get
  # Get configuration
  # Retrieve the current OpenCode configuration settings and preferences.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Config]
  describe 'config_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for config_providers
  # List config providers
  # Get a list of all configured AI providers and their default models.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [ConfigProviders200Response]
  describe 'config_providers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for config_update
  # Update configuration
  # Update OpenCode configuration settings and preferences.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [Config] :config 
  # @return [Config]
  describe 'config_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for event_subscribe
  # Subscribe to events
  # Get events
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Event]
  describe 'event_subscribe test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for experimental_resource_list
  # Get MCP resources
  # Get all available MCP resources from connected servers. Optionally filter by name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Hash<String, McpResource>]
  describe 'experimental_resource_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for file_list
  # List files
  # List files and directories in a specified path.
  # @param path 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<FileNode>]
  describe 'file_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for file_read
  # Read file
  # Read the content of a specified file.
  # @param path 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [FileContent]
  describe 'file_read test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for file_status
  # Get file status
  # Get the git status of all files in the project.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<File>]
  describe 'file_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_files
  # Find files
  # Search for files or directories by name or pattern in the project directory.
  # @param query 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [String] :dirs 
  # @option opts [String] :type 
  # @option opts [Integer] :limit 
  # @return [Array<String>]
  describe 'find_files test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_symbols
  # Find symbols
  # Search for workspace symbols like functions, classes, and variables using LSP.
  # @param query 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<Symbol>]
  describe 'find_symbols test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_text
  # Find text
  # Search for text patterns across files in the project using ripgrep.
  # @param pattern 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<FindText200ResponseInner>]
  describe 'find_text test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for formatter_status
  # Get formatter status
  # Get formatter status
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<FormatterStatus>]
  describe 'formatter_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for global_dispose
  # Dispose instance
  # Clean up and dispose all OpenCode instances, releasing all resources.
  # @param [Hash] opts the optional parameters
  # @return [Boolean]
  describe 'global_dispose test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for global_event
  # Get global events
  # Subscribe to global events from the OpenCode system using server-sent events.
  # @param [Hash] opts the optional parameters
  # @return [GlobalEvent]
  describe 'global_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for global_health
  # Get health
  # Get health information about the OpenCode server.
  # @param [Hash] opts the optional parameters
  # @return [GlobalHealth200Response]
  describe 'global_health test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instance_dispose
  # Dispose instance
  # Clean up and dispose the current OpenCode instance, releasing all resources.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'instance_dispose test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for lsp_status
  # Get LSP status
  # Get LSP server status
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<LSPStatus>]
  describe 'lsp_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_add
  # Add MCP server
  # Dynamically add a new Model Context Protocol (MCP) server to the system.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [McpAddRequest] :mcp_add_request 
  # @return [Hash<String, MCPStatus>]
  describe 'mcp_add test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_auth_authenticate
  # Authenticate MCP OAuth
  # Start OAuth flow and wait for callback (opens browser)
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [MCPStatus]
  describe 'mcp_auth_authenticate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_auth_callback
  # Complete MCP OAuth
  # Complete OAuth authentication for a Model Context Protocol (MCP) server using the authorization code.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [McpAuthCallbackRequest] :mcp_auth_callback_request 
  # @return [MCPStatus]
  describe 'mcp_auth_callback test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_auth_remove
  # Remove MCP OAuth
  # Remove OAuth credentials for an MCP server
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [McpAuthRemove200Response]
  describe 'mcp_auth_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_auth_start
  # Start MCP OAuth
  # Start OAuth authentication flow for a Model Context Protocol (MCP) server.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [McpAuthStart200Response]
  describe 'mcp_auth_start test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_connect
  # Connect an MCP server
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'mcp_connect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_disconnect
  # Disconnect an MCP server
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'mcp_disconnect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mcp_status
  # Get MCP status
  # Get the status of all Model Context Protocol (MCP) servers.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Hash<String, MCPStatus>]
  describe 'mcp_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for part_delete
  # Delete a part from a message
  # @param session_id Session ID
  # @param message_id Message ID
  # @param part_id Part ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'part_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for part_update
  # Update a part in a message
  # @param session_id Session ID
  # @param message_id Message ID
  # @param part_id Part ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [Part] :part 
  # @return [Part]
  describe 'part_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for path_get
  # Get paths
  # Retrieve the current working directory and related path information for the OpenCode instance.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Path]
  describe 'path_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permission_list
  # List pending permissions
  # Get all pending permission requests across all sessions.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<PermissionRequest>]
  describe 'permission_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permission_reply
  # Respond to permission request
  # Approve or deny a permission request from the AI assistant.
  # @param request_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [PermissionReplyRequest] :permission_reply_request 
  # @return [Boolean]
  describe 'permission_reply test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permission_respond
  # Respond to permission
  # Approve or deny a permission request from the AI assistant.
  # @param session_id 
  # @param permission_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [PermissionRespondRequest] :permission_respond_request 
  # @return [Boolean]
  describe 'permission_respond test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for project_current
  # Get current project
  # Retrieve the currently active project that OpenCode is working with.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Project]
  describe 'project_current test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for project_list
  # List all projects
  # Get a list of projects that have been opened with OpenCode.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<Project>]
  describe 'project_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for project_update
  # Update project
  # Update project properties such as name, icon, and commands.
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [ProjectUpdateRequest] :project_update_request 
  # @return [Project]
  describe 'project_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for provider_auth
  # Get provider auth methods
  # Retrieve available authentication methods for all AI providers.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Hash<String, Array<ProviderAuthMethod>>]
  describe 'provider_auth test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for provider_list
  # List providers
  # Get a list of all available AI providers, including both available and connected ones.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [ProviderList200Response]
  describe 'provider_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for provider_oauth_authorize
  # OAuth authorize
  # Initiate OAuth authorization for a specific AI provider to get an authorization URL.
  # @param provider_id Provider ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [ProviderOauthAuthorizeRequest] :provider_oauth_authorize_request 
  # @return [ProviderAuthAuthorization]
  describe 'provider_oauth_authorize test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for provider_oauth_callback
  # OAuth callback
  # Handle the OAuth callback from a provider after user authorization.
  # @param provider_id Provider ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [ProviderOauthCallbackRequest] :provider_oauth_callback_request 
  # @return [Boolean]
  describe 'provider_oauth_callback test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pty_connect
  # Connect to PTY session
  # Establish a WebSocket connection to interact with a pseudo-terminal (PTY) session in real-time.
  # @param pty_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'pty_connect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pty_create
  # Create PTY session
  # Create a new pseudo-terminal (PTY) session for running shell commands and processes.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [PtyCreateRequest] :pty_create_request 
  # @return [Pty]
  describe 'pty_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pty_get
  # Get PTY session
  # Retrieve detailed information about a specific pseudo-terminal (PTY) session.
  # @param pty_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Pty]
  describe 'pty_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pty_list
  # List PTY sessions
  # Get a list of all active pseudo-terminal (PTY) sessions managed by OpenCode.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<Pty>]
  describe 'pty_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pty_remove
  # Remove PTY session
  # Remove and terminate a specific pseudo-terminal (PTY) session.
  # @param pty_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'pty_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pty_update
  # Update PTY session
  # Update properties of an existing pseudo-terminal (PTY) session.
  # @param pty_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [PtyUpdateRequest] :pty_update_request 
  # @return [Pty]
  describe 'pty_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for question_list
  # List pending questions
  # Get all pending question requests across all sessions.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<QuestionRequest>]
  describe 'question_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for question_reject
  # Reject question request
  # Reject a question request from the AI assistant.
  # @param request_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'question_reject test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for question_reply
  # Reply to question request
  # Provide answers to a question request from the AI assistant.
  # @param request_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [QuestionReplyRequest] :question_reply_request 
  # @return [Boolean]
  describe 'question_reply test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_abort
  # Abort session
  # Abort an active session and stop any ongoing AI processing or command execution.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'session_abort test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_command
  # Send command
  # Send a new command to a session for execution by the AI assistant.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionCommandRequest] :session_command_request 
  # @return [SessionPrompt200Response]
  describe 'session_command test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_create
  # Create session
  # Create a new OpenCode session for interacting with AI assistants and managing conversations.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionCreateRequest] :session_create_request 
  # @return [Session]
  describe 'session_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_delete
  # Delete session
  # Delete a session and permanently remove all associated data, including messages and history.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'session_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_diff
  # Get message diff
  # Get the file changes (diff) that resulted from a specific user message in the session.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [String] :message_id 
  # @return [Array<FileDiff>]
  describe 'session_diff test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_fork
  # Fork session
  # Create a new session by forking an existing session at a specific message point.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionForkRequest] :session_fork_request 
  # @return [Session]
  describe 'session_fork test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_init
  # Initialize session
  # Analyze the current application and create an AGENTS.md file with project-specific agent configurations.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionInitRequest] :session_init_request 
  # @return [Boolean]
  describe 'session_init test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_list
  # List sessions
  # Get a list of all OpenCode sessions, sorted by most recently updated.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory Filter sessions by project directory
  # @option opts [Boolean] :roots Only return root sessions (no parentID)
  # @option opts [Float] :start Filter sessions updated on or after this timestamp (milliseconds since epoch)
  # @option opts [String] :search Filter sessions by title (case-insensitive)
  # @option opts [Float] :limit Maximum number of sessions to return
  # @return [Array<Session>]
  describe 'session_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_message
  # Get message
  # Retrieve a specific message from a session by its message ID.
  # @param session_id Session ID
  # @param message_id Message ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [SessionMessages200ResponseInner]
  describe 'session_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_messages
  # Get session messages
  # Retrieve all messages in a session, including user prompts and AI responses.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [Float] :limit 
  # @return [Array<SessionMessages200ResponseInner>]
  describe 'session_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_prompt
  # Send message
  # Create and send a new message to a session, streaming the AI response.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionPromptRequest] :session_prompt_request 
  # @return [SessionPrompt200Response]
  describe 'session_prompt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_prompt_async
  # Send async message
  # Create and send a new message to a session asynchronously, starting the session if needed and returning immediately.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionPromptRequest] :session_prompt_request 
  # @return [nil]
  describe 'session_prompt_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_revert
  # Revert message
  # Revert a specific message in a session, undoing its effects and restoring the previous state.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionRevertRequest] :session_revert_request 
  # @return [Session]
  describe 'session_revert test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_share
  # Share session
  # Create a shareable link for a session, allowing others to view the conversation.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Session]
  describe 'session_share test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_shell
  # Run shell command
  # Execute a shell command within the session context and return the AI&#39;s response.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionShellRequest] :session_shell_request 
  # @return [AssistantMessage]
  describe 'session_shell test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_status
  # Get session status
  # Retrieve the current status of all sessions, including active, idle, and completed states.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Hash<String, SessionStatus>]
  describe 'session_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_summarize
  # Summarize session
  # Generate a concise summary of the session using AI compaction to preserve key information.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionSummarizeRequest] :session_summarize_request 
  # @return [Boolean]
  describe 'session_summarize test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_todo
  # Get session todos
  # Retrieve the todo list associated with a specific session, showing tasks and action items.
  # @param session_id Session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<Todo>]
  describe 'session_todo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_unrevert
  # Restore reverted messages
  # Restore all previously reverted messages in a session.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Session]
  describe 'session_unrevert test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_unshare
  # Unshare session
  # Remove the shareable link for a session, making it private again.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Session]
  describe 'session_unshare test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_update
  # Update session
  # Update properties of an existing session, such as title or other metadata.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [SessionUpdateRequest] :session_update_request 
  # @return [Session]
  describe 'session_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tool_ids
  # List tool IDs
  # Get a list of all available tool IDs, including both built-in tools and dynamically registered tools.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<String>]
  describe 'tool_ids test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tool_list
  # List tools
  # Get a list of available tools with their JSON schema parameters for a specific provider and model combination.
  # @param provider 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<ToolListItem>]
  describe 'tool_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_append_prompt
  # Append TUI prompt
  # Append prompt to the TUI
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [FindText200ResponseInnerPath] :find_text200_response_inner_path 
  # @return [Boolean]
  describe 'tui_append_prompt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_clear_prompt
  # Clear TUI prompt
  # Clear the prompt
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'tui_clear_prompt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_control_next
  # Get next TUI request
  # Retrieve the next TUI (Terminal User Interface) request from the queue for processing.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [TuiControlNext200Response]
  describe 'tui_control_next test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_control_response
  # Submit TUI response
  # Submit a response to the TUI request queue to complete a pending request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [Object] :body 
  # @return [Boolean]
  describe 'tui_control_response test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_execute_command
  # Execute TUI command
  # Execute a TUI command (e.g. agent_cycle)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [TuiExecuteCommandRequest] :tui_execute_command_request 
  # @return [Boolean]
  describe 'tui_execute_command test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_open_help
  # Open help dialog
  # Open the help dialog in the TUI to display user assistance information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'tui_open_help test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_open_models
  # Open models dialog
  # Open the model dialog
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'tui_open_models test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_open_sessions
  # Open sessions dialog
  # Open the session dialog
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'tui_open_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_open_themes
  # Open themes dialog
  # Open the theme dialog
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'tui_open_themes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_publish
  # Publish TUI event
  # Publish a TUI event
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [TuiPublishRequest] :tui_publish_request 
  # @return [Boolean]
  describe 'tui_publish test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_select_session
  # Select session
  # Navigate the TUI to display the specified session.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [TuiSelectSessionRequest] :tui_select_session_request 
  # @return [Boolean]
  describe 'tui_select_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_show_toast
  # Show TUI toast
  # Show a toast notification in the TUI
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [TuiShowToastRequest] :tui_show_toast_request 
  # @return [Boolean]
  describe 'tui_show_toast test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tui_submit_prompt
  # Submit TUI prompt
  # Submit the prompt
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Boolean]
  describe 'tui_submit_prompt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for vcs_get
  # Get VCS info
  # Retrieve version control system (VCS) information for the current project, such as git branch.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [VcsInfo]
  describe 'vcs_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for worktree_create
  # Create worktree
  # Create a new git worktree for the current project and run any configured startup scripts.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [WorktreeCreateInput] :worktree_create_input 
  # @return [Worktree]
  describe 'worktree_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for worktree_list
  # List worktrees
  # List all sandbox worktrees for the current project.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<String>]
  describe 'worktree_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for worktree_remove
  # Remove worktree
  # Remove a git worktree and delete its branch.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [WorktreeRemoveInput] :worktree_remove_input 
  # @return [Boolean]
  describe 'worktree_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for worktree_reset
  # Reset worktree
  # Reset a worktree branch to the primary default branch.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @option opts [WorktreeResetInput] :worktree_reset_input 
  # @return [Boolean]
  describe 'worktree_reset test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
