=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpencodeClient::SessionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SessionApi' do
  before do
    # run before each test
    @api_instance = OpencodeClient::SessionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionApi' do
    it 'should create an instance of SessionApi' do
      expect(@api_instance).to be_instance_of(OpencodeClient::SessionApi)
    end
  end

  # unit tests for session_children
  # Get session children
  # Retrieve all child sessions that were forked from the specified parent session.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Array<Session>]
  describe 'session_children test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for session_get
  # Get session
  # Retrieve detailed information about a specific OpenCode session.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :directory 
  # @return [Session]
  describe 'session_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
