=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ConfigLspAnyOfValueAnyOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ConfigLspAnyOfValueAnyOf do
  #let(:instance) { OpencodeClient::ConfigLspAnyOfValueAnyOf.new }

  describe 'test an instance of ConfigLspAnyOfValueAnyOf' do
    it 'should create an instance of ConfigLspAnyOfValueAnyOf' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ConfigLspAnyOfValueAnyOf)
    end
  end

  describe 'test attribute "disabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Boolean', ["true"])
      # validator.allowable_values.each do |value|
      #   expect { instance.disabled = value }.not_to raise_error
      # end
    end
  end

end
