=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ConfigTui
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ConfigTui do
  #let(:instance) { OpencodeClient::ConfigTui.new }

  describe 'test an instance of ConfigTui' do
    it 'should create an instance of ConfigTui' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ConfigTui)
    end
  end

  describe 'test attribute "scroll_speed"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "scroll_acceleration"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "diff_style"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["auto", "stacked"])
      # validator.allowable_values.each do |value|
      #   expect { instance.diff_style = value }.not_to raise_error
      # end
    end
  end

end
