=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::EventFileWatcherUpdatedProperties
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::EventFileWatcherUpdatedProperties do
  #let(:instance) { OpencodeClient::EventFileWatcherUpdatedProperties.new }

  describe 'test an instance of EventFileWatcherUpdatedProperties' do
    it 'should create an instance of EventFileWatcherUpdatedProperties' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::EventFileWatcherUpdatedProperties)
    end
  end

  describe 'test attribute "file"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "event"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["add", "change", "unlink"])
      # validator.allowable_values.each do |value|
      #   expect { instance.event = value }.not_to raise_error
      # end
    end
  end

end
