=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::FileContentPatch
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::FileContentPatch do
  #let(:instance) { OpencodeClient::FileContentPatch.new }

  describe 'test an instance of FileContentPatch' do
    it 'should create an instance of FileContentPatch' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::FileContentPatch)
    end
  end

  describe 'test attribute "old_file_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "new_file_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "old_header"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "new_header"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "hunks"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "index"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
