=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::FindText200ResponseInnerSubmatchesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::FindText200ResponseInnerSubmatchesInner do
  #let(:instance) { OpencodeClient::FindText200ResponseInnerSubmatchesInner.new }

  describe 'test an instance of FindText200ResponseInnerSubmatchesInner' do
    it 'should create an instance of FindText200ResponseInnerSubmatchesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::FindText200ResponseInnerSubmatchesInner)
    end
  end

  describe 'test attribute "match"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "_end"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
