=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::LogLevel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::LogLevel do
  #let(:instance) { OpencodeClient::LogLevel.new }

  describe 'test an instance of LogLevel' do
    it 'should create an instance of LogLevel' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::LogLevel)
    end
  end

end
