=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ModelCostExperimentalOver200K
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ModelCostExperimentalOver200K do
  #let(:instance) { OpencodeClient::ModelCostExperimentalOver200K.new }

  describe 'test an instance of ModelCostExperimentalOver200K' do
    it 'should create an instance of ModelCostExperimentalOver200K' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ModelCostExperimentalOver200K)
    end
  end

  describe 'test attribute "input"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "output"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cache"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
