=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::PermissionReplyRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::PermissionReplyRequest do
  #let(:instance) { OpencodeClient::PermissionReplyRequest.new }

  describe 'test an instance of PermissionReplyRequest' do
    it 'should create an instance of PermissionReplyRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::PermissionReplyRequest)
    end
  end

  describe 'test attribute "reply"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["once", "always", "reject"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reply = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
