=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ProviderList200ResponseAllInnerModelsValueProvider
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ProviderList200ResponseAllInnerModelsValueProvider do
  #let(:instance) { OpencodeClient::ProviderList200ResponseAllInnerModelsValueProvider.new }

  describe 'test an instance of ProviderList200ResponseAllInnerModelsValueProvider' do
    it 'should create an instance of ProviderList200ResponseAllInnerModelsValueProvider' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ProviderList200ResponseAllInnerModelsValueProvider)
    end
  end

  describe 'test attribute "npm"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
