=begin
#opencode

#opencode api

The version of the OpenAPI document: 0.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::SessionMessages200ResponseInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::SessionMessages200ResponseInner do
  #let(:instance) { OpencodeClient::SessionMessages200ResponseInner.new }

  describe 'test an instance of SessionMessages200ResponseInner' do
    it 'should create an instance of SessionMessages200ResponseInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::SessionMessages200ResponseInner)
    end
  end

  describe 'test attribute "info"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "parts"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
